package com.bitchat.android.ai.report

/**
 * Converts an [ICS213ReportData] into a self-contained HTML string that looks
 * like an official FEMA ICS-213 General Message form.
 *
 * No Android dependencies — fully unit-testable in :resqmesh-ai.
 */
object ICS213ReportGenerator {

    fun generateHtml(data: ICS213ReportData): String = buildString {
        val catCount = data.categories.size
        val msgCount = data.totalMessages

        appendLine("""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; }
  body {
    font-family: 'Courier New', Courier, monospace;
    margin: 24px;
    color: #000;
    background: #fff;
    font-size: 13px;
  }
  .form-title {
    text-align: center;
    font-size: 18px;
    font-weight: bold;
    border: 2px solid #000;
    padding: 8px;
    letter-spacing: 2px;
  }
  .form-subtitle {
    text-align: center;
    font-size: 11px;
    margin: 4px 0 16px 0;
    color: #444;
  }
  table.header-grid {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 14px;
  }
  table.header-grid td {
    border: 1px solid #000;
    padding: 6px 10px;
    font-size: 12px;
    vertical-align: top;
  }
  .label {
    font-weight: bold;
    width: 110px;
    background: #f0f0f0;
    white-space: nowrap;
  }
  .section-title {
    font-weight: bold;
    font-size: 12px;
    border-bottom: 2px solid #000;
    padding: 3px 0;
    margin: 14px 0 8px 0;
    letter-spacing: 1px;
    text-transform: uppercase;
  }
  .category-header {
    font-weight: bold;
    margin: 12px 0 4px 0;
    font-size: 13px;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .priority-label {
    font-size: 10px;
    padding: 0 4px;
    font-weight: bold;
    letter-spacing: 0.5px;
    vertical-align: middle;
  }
  .message-row {
    margin: 3px 0 3px 20px;
    font-size: 12px;
    line-height: 1.5;
  }
  .confidence {
    color: #555;
    font-size: 11px;
  }
  /* Signature block */
  .sig-section {
    margin-top: 20px;
    border: 1px solid #000;
  }
  .sig-section-title {
    font-weight: bold;
    font-size: 11px;
    background: #f0f0f0;
    padding: 3px 8px;
    border-bottom: 1px solid #000;
    letter-spacing: 0.5px;
    text-transform: uppercase;
  }
  .sig-row {
    display: flex;
    border-bottom: 1px solid #ccc;
  }
  .sig-row:last-child { border-bottom: none; }
  .sig-cell {
    flex: 1;
    padding: 6px 10px;
    border-right: 1px solid #ccc;
    font-size: 11px;
  }
  .sig-cell:last-child { border-right: none; }
  .sig-label {
    font-size: 9px;
    color: #555;
    text-transform: uppercase;
    display: block;
    margin-bottom: 2px;
  }
  .sig-value {
    font-size: 12px;
    font-weight: bold;
    display: block;
    min-height: 18px;
  }
  .sig-line-blank {
    display: block;
    border-bottom: 1px solid #000;
    min-height: 18px;
  }
  /* Reply box */
  .reply-box {
    border: 1px solid #999;
    height: 72px;
    margin-top: 6px;
  }
  /* Footer */
  .page-footer {
    margin-top: 18px;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  .mesh-footer {
    font-size: 10px;
    border-top: 1px solid #ccc;
    padding-top: 6px;
    color: #444;
    flex: 1;
  }
  .page-number {
    font-size: 10px;
    color: #444;
    padding-top: 6px;
    white-space: nowrap;
    margin-left: 16px;
  }
</style>
</head>
<body>
""".trimIndent())

        // ── Form title ─────────────────────────────────────────────────────
        appendLine("""  <div class="form-title">ICS-213 &nbsp; GENERAL MESSAGE</div>""")
        appendLine("""  <div class="form-subtitle">Generated by ResQMesh AI &nbsp;·&nbsp; For official emergency coordination use</div>""")

        // ── Header grid ────────────────────────────────────────────────────
        //  Row 1:  TO  |  MSG NO
        //  Row 2:  FROM (Name, Title)  |  DATE  |  TIME
        //  Row 3:  SUBJECT (full width)
        appendLine("""  <table class="header-grid">""")
        appendLine("""    <tr>""")
        appendLine("""      <td class="label">TO:</td>""")
        appendLine("""      <td>${data.to.htmlEscape()}</td>""")
        appendLine("""      <td class="label" style="width:90px">MSG&nbsp;NO:</td>""")
        appendLine("""      <td style="width:160px; font-weight:bold">${data.messageNumber.htmlEscape()}</td>""")
        appendLine("""    </tr>""")
        appendLine("""    <tr>""")
        appendLine("""      <td class="label">FROM:</td>""")
        appendLine("""      <td>${data.from.htmlEscape()}</td>""")
        appendLine("""      <td class="label">DATE:</td>""")
        appendLine("""      <td>${data.date.htmlEscape()}</td>""")
        appendLine("""    </tr>""")
        appendLine("""    <tr>""")
        appendLine("""      <td class="label">CHANNEL:</td>""")
        appendLine("""      <td>${data.channel.htmlEscape()}</td>""")
        appendLine("""      <td class="label">TIME:</td>""")
        appendLine("""      <td>${data.time.htmlEscape()}</td>""")
        appendLine("""    </tr>""")
        appendLine("""    <tr>""")
        appendLine("""      <td class="label">SUBJECT:</td>""")
        appendLine("""      <td colspan="3">${data.subject.htmlEscape()} &mdash; $msgCount incident${if (msgCount != 1) "s" else ""} across $catCount categor${if (catCount != 1) "ies" else "y"}</td>""")
        appendLine("""    </tr>""")
        appendLine("""  </table>""")

        // ── Message body ───────────────────────────────────────────────────
        appendLine("""  <div class="section-title">Message</div>""")

        if (data.categories.isEmpty()) {
            appendLine("""  <p style="color:#777; font-style:italic;">No classified emergency messages.</p>""")
        } else {
            data.categories.forEach { cat ->
                val count = cat.messages.size
                appendLine("""  <div class="category-header">${cat.name.htmlEscape()} &nbsp;<span class="priority-label">[${cat.priority.htmlEscape()}]</span> &nbsp;<span style="font-weight:normal;font-size:12px">(${count} report${if (count != 1) "s" else ""})</span></div>""")
                cat.messages.forEach { msg ->
                    appendLine("""  <div class="message-row">&#8226; <b>${msg.sender.htmlEscape()}</b> [${msg.timestamp.htmlEscape()}] &mdash; &ldquo;${msg.text.htmlEscape()}&rdquo;<span class="confidence"> &nbsp;·&nbsp; ${msg.confidencePct}% accuracy</span></div>""")
                }
            }
        }

        // ── Operator signature block ────────────────────────────────────────
        appendLine("""
  <div class="sig-section" style="margin-top:24px">
    <div class="sig-section-title">Operator (Sender)</div>
    <div class="sig-row">
      <div class="sig-cell" style="flex:2">
        <span class="sig-label">Name</span>
        <span class="sig-value">${data.from.htmlEscape()}</span>
      </div>
      <div class="sig-cell" style="flex:2">
        <span class="sig-label">Position / Title</span>
        <span class="sig-line-blank">&nbsp;</span>
      </div>
      <div class="sig-cell" style="flex:3">
        <span class="sig-label">Signature</span>
        <span class="sig-line-blank">&nbsp;</span>
      </div>
      <div class="sig-cell" style="flex:2">
        <span class="sig-label">Date / Time</span>
        <span class="sig-value" style="font-weight:normal">${data.dateTime.htmlEscape()}</span>
      </div>
    </div>
  </div>
""".trimIndent())

        // ── Supervisor approval block ──────────────────────────────────────
        appendLine("""
  <div class="sig-section">
    <div class="sig-section-title">Supervisor Approval</div>
    <div class="sig-row">
      <div class="sig-cell" style="flex:2">
        <span class="sig-label">Name</span>
        <span class="sig-line-blank">&nbsp;</span>
      </div>
      <div class="sig-cell" style="flex:2">
        <span class="sig-label">Position / ICS Section</span>
        <span class="sig-line-blank">&nbsp;</span>
      </div>
      <div class="sig-cell" style="flex:3">
        <span class="sig-label">Signature</span>
        <span class="sig-line-blank">&nbsp;</span>
      </div>
      <div class="sig-cell" style="flex:2">
        <span class="sig-label">Date / Time</span>
        <span class="sig-line-blank">&nbsp;</span>
      </div>
    </div>
  </div>
""".trimIndent())

        // ── Reply section ──────────────────────────────────────────────────
        appendLine("""  <div class="section-title" style="margin-top:20px">Reply</div>""")
        appendLine("""  <div class="reply-box"></div>""")

        // ── Footer with mesh metadata + page number ────────────────────────
        appendLine("""
  <div class="page-footer">
    <div class="mesh-footer">
      Mesh channel: ${data.channel.htmlEscape()} &nbsp;|&nbsp;
      Peers connected: ${data.peersConnected} &nbsp;|&nbsp;
      Classifier: ${data.classifierVersion.htmlEscape()} &nbsp;|&nbsp;
      Generated: ${data.dateTime.htmlEscape()}
    </div>
    <div class="page-number">Page 1 of 1</div>
  </div>
""".trimIndent())

        appendLine("</body>")
        appendLine("</html>")
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private fun String.htmlEscape(): String = this
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&#39;")
}
