package com.bitchat.android.ai.report

/**
 * Converts an [ICS213ReportData] into a self-contained HTML string that looks
 * like an official FEMA ICS-213 General Message form.
 *
 * No Android dependencies — fully unit-testable in :disastermesh-ai.
 */
object ICS213ReportGenerator {

    fun generateHtml(data: ICS213ReportData): String = buildString {
        val catCount = data.categories.size
        val msgCount = data.totalMessages

        appendLine("""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; }
  body {
    font-family: 'Courier New', Courier, monospace;
    margin: 24px;
    color: #000;
    background: #fff;
    font-size: 13px;
  }
  .form-title {
    text-align: center;
    font-size: 18px;
    font-weight: bold;
    border: 2px solid #000;
    padding: 8px;
    letter-spacing: 2px;
  }
  .form-subtitle {
    text-align: center;
    font-size: 11px;
    margin: 4px 0 16px 0;
    color: #444;
  }
  table.header-grid {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 14px;
  }
  table.header-grid td {
    border: 1px solid #000;
    padding: 6px 10px;
    font-size: 12px;
    vertical-align: top;
  }
  .label {
    font-weight: bold;
    width: 110px;
    background: #f0f0f0;
    white-space: nowrap;
  }
  .section-title {
    font-weight: bold;
    font-size: 12px;
    border-bottom: 2px solid #000;
    padding: 3px 0;
    margin: 14px 0 8px 0;
    letter-spacing: 1px;
    text-transform: uppercase;
  }
  .category-header {
    font-weight: bold;
    margin: 12px 0 4px 0;
    font-size: 13px;
  }
  .message-row {
    margin: 3px 0 3px 20px;
    font-size: 12px;
    line-height: 1.5;
  }
  .confidence {
    color: #555;
    font-size: 11px;
  }
  .signature-block {
    margin-top: 28px;
  }
  .sig-row {
    display: flex;
    gap: 32px;
    margin-top: 8px;
  }
  .sig-field {
    flex: 1;
  }
  .sig-line {
    border-bottom: 1px solid #000;
    height: 28px;
    display: block;
    margin-bottom: 3px;
  }
  .sig-caption {
    font-size: 10px;
    color: #333;
  }
  .reply-box {
    border: 1px solid #999;
    height: 72px;
    margin-top: 6px;
  }
  .mesh-footer {
    margin-top: 18px;
    font-size: 10px;
    border-top: 1px solid #ccc;
    padding-top: 6px;
    color: #444;
  }
</style>
</head>
<body>
""".trimIndent())

        // ── Form title ─────────────────────────────────────────────────────
        appendLine("""  <div class="form-title">ICS-213 &nbsp; GENERAL MESSAGE</div>""")
        appendLine("""  <div class="form-subtitle">Generated by DisasterMesh &nbsp;·&nbsp; For official emergency coordination use</div>""")

        // ── Header grid ────────────────────────────────────────────────────
        appendLine("""  <table class="header-grid">""")
        appendLine("""    <tr>""")
        appendLine("""      <td class="label">TO:</td><td>${data.to.htmlEscape()}</td>""")
        appendLine("""      <td class="label">DATE:</td><td>${data.date.htmlEscape()}</td>""")
        appendLine("""    </tr>""")
        appendLine("""    <tr>""")
        appendLine("""      <td class="label">FROM:</td><td>${data.from.htmlEscape()}</td>""")
        appendLine("""      <td class="label">TIME:</td><td>${data.time.htmlEscape()}</td>""")
        appendLine("""    </tr>""")
        appendLine("""    <tr>""")
        appendLine("""      <td class="label">SUBJECT:</td>""")
        appendLine("""      <td colspan="3">${data.subject.htmlEscape()} &mdash; $msgCount incident${if (msgCount != 1) "s" else ""} across $catCount categor${if (catCount != 1) "ies" else "y"}</td>""")
        appendLine("""    </tr>""")
        appendLine("""  </table>""")

        // ── Message body ───────────────────────────────────────────────────
        appendLine("""  <div class="section-title">Message</div>""")

        if (data.categories.isEmpty()) {
            appendLine("""  <p style="color:#777; font-style:italic;">No classified emergency messages.</p>""")
        } else {
            data.categories.forEach { cat ->
                val count = cat.messages.size
                appendLine("""  <div class="category-header">${cat.emoji.htmlEscape()} ${cat.name.htmlEscape()} &nbsp;(${count} report${if (count != 1) "s" else ""})</div>""")
                cat.messages.forEach { msg ->
                    appendLine("""  <div class="message-row">&#8226; ${msg.sender.htmlEscape()} [${msg.timestamp.htmlEscape()}] &mdash; &ldquo;${msg.text.htmlEscape()}&rdquo;<span class="confidence"> &nbsp;·&nbsp; ${msg.confidencePct}% confidence</span></div>""")
                }
            }
        }

        // ── Signature block ────────────────────────────────────────────────
        appendLine("""
  <div class="signature-block">
    <div class="section-title">Approved By</div>
    <div class="sig-row">
      <div class="sig-field">
        <span class="sig-line">&nbsp;</span>
        <span class="sig-caption">Name / Position</span>
      </div>
      <div class="sig-field">
        <span class="sig-line">&nbsp;</span>
        <span class="sig-caption">Signature</span>
      </div>
      <div class="sig-field">
        <span class="sig-line">&nbsp;</span>
        <span class="sig-caption">Date / Time</span>
      </div>
    </div>
  </div>
""".trimIndent())

        // ── Reply section ──────────────────────────────────────────────────
        appendLine("""  <div class="section-title">Reply</div>""")
        appendLine("""  <div class="reply-box"></div>""")

        // ── Mesh metadata footer ───────────────────────────────────────────
        appendLine("""
  <div class="mesh-footer">
    Mesh channel: ${data.channel.htmlEscape()} &nbsp;|&nbsp;
    Peers connected: ${data.peersConnected} &nbsp;|&nbsp;
    Classifier: ${data.classifierVersion.htmlEscape()} &nbsp;|&nbsp;
    Generated: ${data.dateTime.htmlEscape()}
  </div>
""".trimIndent())

        appendLine("</body>")
        appendLine("</html>")
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private fun String.htmlEscape(): String = this
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&#39;")
}
